// frostgfx_simple.cpp - Stub implementation.
//
// The real impl would hold a coregfx::api::FrostEngine and forward each
// method to it, constructing the appropriate CmdXxx variant internally.

#include "frostgfx_simple.hpp"
#include "poc-02-cxx-bridge/src/main.rs.h"   // generated by cxx-build

namespace frostgfx_simple {

FrostEngineSimple::FrostEngineSimple()  = default;
FrostEngineSimple::~FrostEngineSimple() = default;

bool FrostEngineSimple::initialize(const EngineConfigDto& cfg) {
    // Real: build coregfx::api::EngineConfig, send CmdInitialize.
    (void)cfg;
    state_ = 1; // Ready
    entities_.clear();
    return true;
}

bool FrostEngineSimple::load_scene(rust::Str scene_uri, bool preview_only) {
    (void)preview_only;
    if (scene_uri.empty()) {
        last_error_ = "scene_uri is empty";
        return false;
    }
    state_ = 2; // SceneLoaded
    entities_ = {"player", "camera_main", "directional_light"};
    return true;
}

bool FrostEngineSimple::update_camera(const Camera& cam) {
    (void)cam;
    return state_ >= 1;
}

bool FrostEngineSimple::activate() {
    if (state_ < 2) {
        last_error_ = "load a scene before activate()";
        return false;
    }
    state_ = 3; // Running
    return true;
}

bool FrostEngineSimple::shutdown() {
    state_ = 4; // ShuttingDown
    return true;
}

int32_t FrostEngineSimple::state() const { return state_; }

rust::String FrostEngineSimple::last_error() const {
    return rust::String(last_error_);
}

rust::Vec<rust::String> FrostEngineSimple::list_entities() const {
    rust::Vec<rust::String> out;
    for (const auto& id : entities_) out.push_back(rust::String(id));
    return out;
}

std::unique_ptr<FrostEngineSimple> new_engine() {
    return std::make_unique<FrostEngineSimple>();
}

} // namespace frostgfx_simple
