[package]
name = "poc-07-tauri-vue"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lib]
name = "poc_07_tauri_vue_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "poc-07-tauri-vue"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
