// frostgfx_bridge.cpp - Forwards a curated subset of FrostEngine to Rust.
//
// Limits in this first iteration:
//   - Only CmdInitialize is exercised; the engine is *not* activate()-d
//     because that would try to open a Vulkan device + a window.
//   - getState() is read via FrostEngine::getState() which is documented as
//     an atomic read (no command queueing).
// Extend by adding more wrapper methods that each construct one CmdXxx and
// call engine_.send(...) — the variant fan-out lives here, not in Rust.

#include "frostgfx_bridge.hpp"
#include "poc-05-frostgfx-cxx/src/main.rs.h"  // generated by cxx-build

#include <frostgfx/api/FrostCommands.hpp>
#include <frostgfx/api/FrostResponse.hpp>
#include <frostgfx/frostgfx.h>  // for frostgfx_version_string()

#include <string>

namespace fgx_bridge {

int32_t FrostEngineWrapper::state() const {
    return static_cast<int32_t>(engine_.getState());
}

bool FrostEngineWrapper::initialize(const EngineConfigDto& cfg) {
    coregfx::api::EngineConfig c;
    c.windowTitle       = std::string(cfg.window_title);
    c.windowWidth       = cfg.window_width;
    c.windowHeight      = cfg.window_height;
    c.vsync             = cfg.vsync;
    c.validationEnabled = cfg.validation_enabled;
    c.headless          = cfg.headless;
    // parent_window_handle stays nullptr for this POC; the field exists
    // in EngineConfig for HWND embedding (poc-03 covers that wiring).

    auto resp = engine_.send(coregfx::api::CmdInitialize{ std::move(c) });
    return resp.status == coregfx::api::ResponseStatus::Ok;
}

std::unique_ptr<FrostEngineWrapper> new_engine() {
    return std::make_unique<FrostEngineWrapper>();
}

rust::String frostgfx_version() {
    return rust::String(frostgfx_version_string());
}

} // namespace fgx_bridge
